services:
  cvmfs-server:
    build:
      context: .
      target: server
    
    ports:
      # cvmfs file server
      - "8080:80"
      # application server
      - "8081:81"
      # cvmfs gateway
      - "4929:4929"
    
    volumes:
      - ./server/src:/app
      # Persist the keys so that the client doesn't need to be reconfigured
      - ./tmp/cvmfs-keys:/etc/cvmfs/keys/
    
    tmpfs:
      # use ephemeral data directory for testing
      - /srv
      # Required (placing /var/spool/cvmfs in both tmpfs and bind mount both work. Make sure to clean this up if using bind mount). Otherwise will get the following error:
      #   Mounting CernVM-FS Storage... (overlayfs) mount: /cvmfs/cvmfs.cluster.watonomous.ca: wrong fs type, bad option, bad superblock on overlay_cvmfs.cluster.watonomous.ca, missing codepage or helper program, or other error.
      # https://cernvm-forum.cern.ch/t/overlayfs-on-top-of-cephfs/120/4
      - /var/spool/cvmfs
    
    cap_add:
      - SYS_ADMIN # required for fuse and ducc: https://cernvm-forum.cern.ch/t/where-to-get-cvmfs-ducc-binary/366/2
      - DAC_OVERRIDE # required by ducc: https://cernvm-forum.cern.ch/t/where-to-get-cvmfs-ducc-binary/366/2
      - DAC_READ_SEARCH # required by ducc: https://cernvm-forum.cern.ch/t/where-to-get-cvmfs-ducc-binary/366/2
      - FOWNER # required by ducc: https://cernvm-forum.cern.ch/t/where-to-get-cvmfs-ducc-binary/366/2
      - CHOWN # required by ducc: https://cernvm-forum.cern.ch/t/where-to-get-cvmfs-ducc-binary/366/2
      - MKNOD # required by ducc: https://cernvm-forum.cern.ch/t/where-to-get-cvmfs-ducc-binary/366/2
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse
  
  cvmfs-publisher:
    build:
      context: .
      target: publisher

    volumes:
      - ./tmp/cvmfs-keys:/tmp/imported-keys:ro
    
    tmpfs:
      - /var/spool/cvmfs

    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse
